# Generated by Django 5.0.1 on 2024-02-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_confirmationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
