# Generated by Django 5.0.1 on 2024-02-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_playermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefendersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('position', models.TextField()),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='defend')),
            ],
            options={
                'verbose_name': 'defend',
                'verbose_name_plural': 'defenders',
            },
        ),
    ]
