# Generated by Django 5.0.1 on 2024-02-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_defendersmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defendersmodel',
            options={'verbose_name': 'defend', 'verbose_name_plural': 'defenders  '},
        ),
    ]
