# Generated by Django 5.0.1 on 2024-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_managermodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
                ('city1', models.TextField()),
                ('city2', models.TextField()),
                ('balance1', models.IntegerField()),
                ('balance2', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.IntegerField()),
                ('image1', models.ImageField(upload_to='matches')),
                ('image2', models.ImageField(upload_to='matches')),
                ('turnir', models.TextField()),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
    ]
