# Generated by Django 5.0.1 on 2024-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_goalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('score', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'assist',
                'verbose_name_plural': 'assisters',
            },
        ),
    ]
